#!/bin/bash

# Import common functions
. common.sh

turn_off_after="$1"

home_path="/home/gudbjorn.einarsson"
code_path="$home_path/ml_train_cloud_test"
train_script_server="train_script_server"
mount_script_server="mount_cloud_fs"
tb_output_dir="$home_path/tb_output"
bucket_name="machinelearningcloudbucket"
python_run_script="$code_path/main2.py"
server_instance_name="instance-3"

is_running=$(is_instance_running "$server_instance_name")

if [ "$is_running" = "not_running" ]; then
  start_instance "$server_instance_name"
  
  wait_for_ssh_to_be_ready "$server_instance_name"

  echo "Instance started"
  gcloud compute ssh gudbjorn.einarsson@"$server_instance_name" --command "bash $code_path/$mount_script_server $tb_output_dir $bucket_name"
else
  echo "Instance already running"
fi

gcloud compute ssh gudbjorn.einarsson@"$server_instance_name" --command "bash $code_path/$train_script_server $tb_output_dir $python_run_script $code_path"
echo "Instance command finished"

if [ "$turn_off_after" = "turnoff" ]; then
  gcloud compute instances stop "$server_instance_name"
  echo "Instance stopped"
fi


