#!/bin/bash

tb_output="$1"
python_training_file="$2"
python_file_params ="$3"
code_location="$4"
virtual_env_location="$5"

#echo "From server script. tb_output: $tb_output"
#echo "From server script. python_training_file: $python_training_file"

# Must be in correct folder to do git pull and other stuff
cd "$code_location"

# Update code
git pull
echo "git pull done"

# Source the correct python3 venv
source "$virtual_env_location"/bin/activate

# Run the training scrypt
echo "About to run training script"
python3 "$python_training_file" --tb_output "$tb_output"

# Unmount the cloud fs and delete the output folder
fusermount -u "$tb_output"
rm -rf "$tb_output"



