#!/bin/bash

tb_output="$1"
python_training_file="$2"
code_location="$3"
virtual_env_location="$4"
python_params="${@:5}"

#echo "From server script. tb_output: $tb_output"
#echo "From server script. python_training_file: $python_training_file"

# Must be in correct folder to do git pull and other stuff
cd "$code_location"

# Update code
git pull
echo "git pull done"

# Source the correct python3 venv
source "$virtual_env_location"/bin/activate

# Run the training scrypt
echo "About to run training script"
python3 "$python_training_file" --log_path "$tb_output" ${python_params}

# Unmount the cloud fs
fusermount -u "$tb_output"



